shinyUI(fluidPage(theme = shinytheme("slate"),

                  navbarPage(title = HTML('<a href="https://paulpnd.github.io/ProjetMongo"> Retour à la page principale du projet </a>'),
                                        tabPanel("Carte",
                                                 HTML("<p>Cette carte permet de voir quels sont les restaurants les mieux notés de New York. </br>
                                                   Elle affiche les 10 restaurants ayant obtenu les meilleurs notes selon le quartier et le type de cuisine sélectionnés. </br>
                                                   Les couleurs sont échelonnées à partir des 10 restaurants obtenus, afin de voir quel sont les meilleurs restaurants parmis les meilleurs. </br>
                                                   Les zones de choix de variables peuvent être déplacées afin de ne pas gêner la visualisation.
                                                      </p>"),
                                                 div(class = "outer",
                                                     tags$head(includeCSS("styles.css")),
                                                     
                                                     leafletOutput("map_ny", height = "80vh"),
                                                     
                                                     absolutePanel(id = "controls", class = "panel panel-default",
                                                                   top = 200, left = 100, width = 250, fixed=TRUE,
                                                                   draggable = TRUE, height = "auto",
                                                                   
                                                                   selectInput("quartier", label = h3("Quartier choisi :"),
                                                                               choices = list("Tous les quartiers",
                                                                                              "Brooklyn" = "Brooklyn",
                                                                                              "Bronx" = "Bronx",
                                                                                              "Manhattan" = "Manhattan",
                                                                                              "Queens" = "Queens",
                                                                                              "Staten Island" = "Staten Island", 
                                                                                              "Missing" = "Missing"),
                                                                               selected = "Tous les quartiers")
                                                                   
                                                     ),
                                                     absolutePanel(id = "controls", class = "panel panel-default",
                                                                   top = 200, left = 350, width = 250, fixed=TRUE,
                                                                   draggable = TRUE, height = "auto",
                                                                   
                                                                   selectInput("type_cuisine", label = h3("Type de cuisine choisi :"),
                                                                               choices = list("Tous les types de cuisine",
                                                                                              "Juice, Smoothies, Fruit Salads" = "Juice, Smoothies, Fruit Salads" ,
                                                                                              "Chinese" = "Chinese" ,
                                                                                              "Bakery" = "Bakery" ,
                                                                                              "Japanese" = "Japanese" ,
                                                                                              "Café/Coffee/Tea" = "Café/Coffee/Tea" ,
                                                                                              "Middle Eastern" = "Middle Eastern" ,
                                                                                              "Other" = "Other" ,
                                                                                              "American " = "American " ,
                                                                                              "Pizza" = "Pizza" ,
                                                                                              "Mexican" = "Mexican" ,
                                                                                              "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin (Cuban, Dominican, Puerto Rican, South & Central American)",
                                                                                              "French" = "French" ,
                                                                                              "Chinese/Japanese" = "Chinese/Japanese" ,
                                                                                              "Caribbean" = "Caribbean" ,
                                                                                              "Spanish" = "Spanish" ,
                                                                                              "Ice Cream, Gelato, Yogurt, Ices" = "Ice Cream, Gelato, Yogurt, Ices" ,
                                                                                              "Korean" = "Korean" ,
                                                                                              "Vietnamese/Cambodian/Malaysia" = "Vietnamese/Cambodian/Malaysia" ,
                                                                                              "Thai" = "Thai" ,
                                                                                              "Pizza/Italian" = "Pizza/Italian" ,
                                                                                              "Bangladeshi" = "Bangladeshi" ,
                                                                                              "Indian" = "Indian" ,
                                                                                              "Chicken" = "Chicken" ,
                                                                                              "Australian" = "Australian" ,
                                                                                              "Asian" = "Asian" ,
                                                                                              "Italian" = "Italian" ,
                                                                                              "Tex-Mex" = "Tex-Mex" ,
                                                                                              "Delicatessen" = "Delicatessen" ,
                                                                                              "Brazilian" = "Brazilian" ,
                                                                                              "Seafood" = "Seafood" ,
                                                                                              "Jewish/Kosher" = "Jewish/Kosher" ,
                                                                                              "Continental" = "Continental" ,
                                                                                              "Pakistani" = "Pakistani" ,
                                                                                              "Turkish" = "Turkish" ,
                                                                                              "Vegetarian" = "Vegetarian" ,
                                                                                              "Russian" = "Russian" ,
                                                                                              "Creole" = "Creole" ,
                                                                                              "African" = "African" ,
                                                                                              "Bagels/Pretzels" = "Bagels/Pretzels" ,
                                                                                              "Sandwiches/Salads/Mixed Buffet" = "Sandwiches/Salads/Mixed Buffet" ,
                                                                                              "Eastern European" = "Eastern European" ,
                                                                                              "German" = "German" ,
                                                                                              "Mediterranean" = "Mediterranean" ,
                                                                                              "Irish" = "Irish" ,
                                                                                              "Armenian" = "Armenian" ,
                                                                                              "Peruvian" = "Peruvian" ,
                                                                                              "Hamburgers" = "Hamburgers" ,
                                                                                              "Sandwiches" = "Sandwiches" ,
                                                                                              "Soul Food" = "Soul Food" ,
                                                                                              "Polish" = "Polish" ,
                                                                                              "Chinese/Cuban" = "Chinese/Cuban" ,
                                                                                              "Steak" = "Steak" ,
                                                                                              "Tapas" = "Tapas" ,
                                                                                              "Moroccan" = "Moroccan" ,
                                                                                              "Filipino" = "Filipino" ,
                                                                                              "Donuts" = "Donuts" ,
                                                                                              "English" = "English" ,
                                                                                              "Barbecue" = "Barbecue" ,
                                                                                              "Greek" = "Greek" ,
                                                                                              "Pancakes/Waffles" = "Pancakes/Waffles" ,
                                                                                              "Bottled beverages, including water, sodas, juices, etc." = "Bottled beverages, including water, sodas, juices, etc." ,
                                                                                              "Soups & Sandwiches" = "Soups & Sandwiches" ,
                                                                                              "Hotdogs/Pretzels" = "Hotdogs/Pretzels" ,
                                                                                              "Iranian" = "Iranian" ,
                                                                                              "Hawaiian" = "Hawaiian" ,
                                                                                              "Ethiopian" = "Ethiopian" ,
                                                                                              "Southwestern" = "Southwestern" ,
                                                                                              "Soups" = "Soups" ,
                                                                                              "Scandinavian" = "Scandinavian" ,
                                                                                              "Portuguese" = "Portuguese" ,
                                                                                              "Afghan" = "Afghan" ,
                                                                                              "Indonesian" = "Indonesian" ,
                                                                                              "Not Listed/Not Applicable" = "Not Listed/Not Applicable" ,
                                                                                              "Polynesian" = "Polynesian" ,
                                                                                              "Egyptian" = "Egyptian" ,
                                                                                              "Hotdogs" = "Hotdogs" ,
                                                                                              "Salads" = "Salads" ,
                                                                                              "CafÃ©/Coffee/Tea" = "CafÃ©/Coffee/Tea" ,
                                                                                              "Cajun" = "Cajun" ,
                                                                                              "Czech" = "Czech" ,
                                                                                              "Nuts/Confectionary" = "Nuts/Confectionary" ,
                                                                                              "Californian" = "Californian"
                                                                                              
                                                                               ),
                                                                               selected = "Tous les types de cuisine")
                                                                   
                                                     )
                                                   )
                                        )

)
)
)